# ============ Window ============
background_opacity 0.7
dynamic_title yes
window_decorations full
window_padding_width 8 6

# ============ Font ============
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 10.0

# ============ Colors ============
foreground #cfc6ff
background #1e1b29

color0  #1e1b29
color1  #ff5c93
color2  #a8ff60
color3  #ffd700
color4  #5a3dad
color5  #a183ff
color6  #00d3d0
color7  #cfc6ff

color8  #44475a
color9  #ff6e96
color10 #b0ff87
color11 #ffe066
color12 #7b5cf2
color13 #bd99ff
color14 #33f6f4
color15 #ffffff

# ============ Cursor ============
cursor_shape block
cursor_blink_interval 1.0
cursor_stop_blinking_after 0

# ============ Selection ============
copy_on_select yes

# ============ Shell ============
shell /bin/zsh

